services:
  web:
    build: .
    ports:
      - "8000:8000"  # Expose the app on port 8000
    volumes:
      - .:/app  # Bind the current directory to /app in the container
    command: python manage.py runserver 0.0.0.0:8000  # Run the development server